### ISSUE TITLE
Not working automatically

### ISSUE THREAD

**Issue by Igortorrente** [tikhomirov/vim-glsl#18] opened 2020-07-08 01:49 UTC
Hi,
I installed this plugin using Vundle by following the [vim awesome](https://vimawesome.com/plugin/vim-glsl) instructions.
But for some reason, it is not automatically highlighting my shader files.
Only works if  I type manually `autocmd! BufNewFile,BufRead *.vert,*.tesc,*.tese,*.glsl,*.geom,*.frag,*.comp set filetype=glsl`. Do you have any idea what is going on?

**Comment by Igortorrente** [comment] 2020-07-21 21:09
A quick workaround is put `autocmd BufNewFile,BufRead *.vert,*.tesc,*.tese,*.glsl,*.geom,*.frag,*.comp set filetype=glsl`  in .vimrc.

**Comment by tikhomirov** [comment] 2021-09-05 17:29
Cannot reproduce. Tested on clean `.vim` directory and the latest version of Vundle. Here is the contents of the test `.vimrc`:

```vim
set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'tikhomirov/vim-glsl'

call vundle#end()
filetype plugin indent on  
```
Filetype is detected correctly and syntax highlighting works as expected. Tested with supported file extensions.

**Comment by tikhomirov** [comment] 2021-09-05 17:31
@Igortorrente I'm closing the issue. If it still doesn't work for you, please reopen the issue with more details so I can reproduce it.

**Closed by tikhomirov** 2021-09-05 17:31 UTC

**Comment by Igortorrente** [comment] 2021-09-06 14:52
I still can reproduce the issue. Here is my [`.vimrc`](https://gist.github.com/Igortorrente/81aac8b5388429442c47c563296b99e5). 

``` console
$ vim --version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar 02 2021 02:58:09)

$ nvim --version
NVIM v0.4.4
Build type: Release
LuaJIT 2.1.0-beta3
```

There's any other information that you would require?

**Comment by presentfactory** [comment] 2021-09-21 12:43
I am having this issue too, comparing my `.vimrc` to the other one causing the issue above I do notice that we both have `syntastic` installed, so perhaps it is something to do with that. The full list of plugins I have running along with it for reference is:
```
Plug 'Raimondi/delimitMate'
Plug 't9md/vim-quickhl'
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'itchyny/lightline.vim'
Plug 'preservim/nerdtree'
Plug 'bfrg/vim-cpp-modern'
Plug 'ycm-core/YouCompleteMe'
Plug 'vim-syntastic/syntastic'
Plug 'ziglang/zig.vim'
Plug 'tikhomirov/vim-glsl'
```

**Comment by Igortorrente** [comment] 2021-09-21 12:45
Acttually, syntastric is the only plugin that I don't have installed because I

**Comment by Igortorrente** [comment] 2021-09-21 13:15
Actually, syntastic is the only plugin that I don't have installed. It's commented since 2017 because I never spent the time to configure it.

I disabled all the plugins, for test purposes, and the issue persists.
